/*------------------------------
ALUNO: GABRIEL SANTANA CRUZ
MATRICULA: 201500258956

AVALIAÇÃO 1 - BANCO DE DADOS 2
------------------------------*/

/* ------------------ QUESTÃO 01 ------------------ */
CREATE PROCEDURE SP_VALOR_PLANO(@COD_PLANO INT, @DATA_NASCIMENTO DATETIME, @DATA_FATURA DATETIME, @VALOR_PLANO NUMERIC(10,2) OUTPUT)
AS
BEGIN
	DECLARE @IDADEATUAL INT

	SET @IDADEATUAL = DATEDIFF(MM, @DATA_NASCIMENTO, @DATA_FATURA)/12

	SET @VALOR_PLANO = (SELECT VALOR FROM TB_VALOR_BASE_PLANO WHERE IDADE_MENOR <= @IDADEATUAL AND IDADE_MAIOR >= @IDADEATUAL AND COD_PLANO = @COD_PLANO)
END

/* ------------------ QUESTÃO 02 ------------------ */
CREATE PROCEDURE SP_POSSUI_ATENDIMENTO(@CPF VARCHAR(13), @DATA_FATURA DATETIME, @TEMCONSULTA TINYINT OUTPUT)
AS
BEGIN
	DECLARE @QTDCONSULTA INT

	SET @QTDCONSULTA = (SELECT COUNT(COD_ATENDIMENTO) FROM TB_ATENDIMENTOS WHERE CPF = @CPF AND DATEPART(MM, DT_ATENDIMENTO) = DATEPART(MM, @DATA_FATURA))

	IF(@QTDCONSULTA >= 1)
		SET @TEMCONSULTA = 1
	ELSE
		SET @TEMCONSULTA = 0
END

/* ------------------ QUESTÃO 03 ------------------ */
CREATE PROCEDURE SP_GERAR_BOLETO(@DATA_FATURA DATETIME)
AS
BEGIN
	DECLARE @TITULAR VARCHAR(100), @CPF VARCHAR(13), @NOMEPLANO VARCHAR(100), @VALORPLANO NUMERIC(10,2), @TOTALBOLETO NUMERIC(10,2), @MATRICULA INT, @DATA_NASCIMENTO DATETIME, @COD_PLANO INT

	-- CURSOR
	DECLARE CURSOR_GERAL CURSOR
	FOR
	SELECT MATRICULA, NOME, CPF, DT_NASCIMENTO, COD_PLANO FROM TB_CLIENTE

	OPEN CURSOR_GERAL
	FETCH CURSOR_GERAL INTO @MATRICULA, @TITULAR, @CPF, @DATA_NASCIMENTO, @COD_PLANO

	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		SET @NOMEPLANO = (SELECT DESC_PLANO FROM TB_PLANO WHERE COD_PLANO = @COD_PLANO)
		SET @TOTALBOLETO = 0

		PRINT('------------------------------')
		PRINT('TITULAR: ' + @TITULAR)
		PRINT('CPF TITULAR: ' + @CPF)
		PRINT('PLANO: ' + @NOMEPLANO)
		PRINT('------------------------------')
		PRINT('NOME' + CHAR(9) + CHAR(9) + CHAR(9) + CHAR(9) + 'VALOR')

		
		DECLARE @NASCIMENTO_DEPENDENTE DATETIME, @NOME_DEPENDENTE VARCHAR(100)

		EXEC SP_VALOR_PLANO @COD_PLANO,@DATA_NASCIMENTO,@DATA_FATURA, @VALORPLANO OUTPUT

		DECLARE @POSSUI_ATENDIMENTO TINYINT, @FATOR NUMERIC(10,2)

		EXEC SP_POSSUI_ATENDIMENTO @CPF, @DATA_FATURA, @POSSUI_ATENDIMENTO OUTPUT

		SET @FATOR = (SELECT FATOR_MODERADOR FROM TB_PLANO WHERE COD_PLANO = @COD_PLANO)

		IF(@POSSUI_ATENDIMENTO >= 1)
			SET @VALORPLANO = @VALORPLANO + @FATOR


		SET @TOTALBOLETO = @VALORPLANO

		PRINT(@TITULAR + CHAR(9) + CHAR(9) + STR(@VALORPLANO))

		DECLARE CURSOR_DEPEN CURSOR
		FOR
		SELECT NOME, DT_NASCIMENTO, CPF FROM TB_DEPENDENTES WHERE MATRICULA = @MATRICULA

		OPEN CURSOR_DEPEN
		FETCH CURSOR_DEPEN INTO @NOME_DEPENDENTE, @NASCIMENTO_DEPENDENTE, @CPF

		WHILE(@@FETCH_STATUS = 0)
		BEGIN
			DECLARE @V_DEPEN NUMERIC(10,2)

			SET @V_DEPEN = 0

			EXEC SP_POSSUI_ATENDIMENTO @CPF, @DATA_FATURA, @POSSUI_ATENDIMENTO OUTPUT

			EXEC SP_VALOR_PLANO @COD_PLANO, @NASCIMENTO_DEPENDENTE, @DATA_FATURA, @VALORPLANO OUTPUT

			IF(@POSSUI_ATENDIMENTO >= 1)
				SET @VALORPLANO = @VALORPLANO + @FATOR

			SET @V_DEPEN = @V_DEPEN + @VALORPLANO

			SET @TOTALBOLETO = @TOTALBOLETO + @V_DEPEN

			PRINT(@NOME_DEPENDENTE + CHAR(9) + CHAR(9) + STR(@VALORPLANO))

			FETCH CURSOR_DEPEN INTO @NOME_DEPENDENTE, @NASCIMENTO_DEPENDENTE, @CPF
		END

		CLOSE CURSOR_DEPEN
		DEALLOCATE CURSOR_DEPEN

		PRINT('')
		PRINT('TOTAL' + CHAR(9) + CHAR(9) + CHAR(9) + STR(@TOTALBOLETO))

		FETCH CURSOR_GERAL INTO @MATRICULA, @TITULAR, @CPF, @DATA_NASCIMENTO, @COD_PLANO
	END

	CLOSE CURSOR_GERAL
	DEALLOCATE CURSOR_GERAL
END

DROP PROCEDURE SP_VALOR_PLANO
DROP PROCEDURE SP_POSSUI_ATENDIMENTO
DROP PROCEDURE SP_GERAR_BOLETO

EXEC SP_GERAR_BOLETO '20190731'