CREATE TABLE TB_USUARIO (
  CD_USUARIO INT NOT NULL PRIMARY KEY,
  NM_USUARIO VARCHAR(60) NOT NULL,
  CPF INT NULL
)

CREATE TABLE TB_LANCAMENTOS (
   CD_LANCAMENTO INT NOT NULL PRIMARY KEY IDENTITY(1,1),
   MES INT NOT NULL,
   ANO INT NOT NULL,
   CD_USUARIO INT NOT NULL,
   TP_LANCAMENTO VARCHAR(1) CHECK (TP_LANCAMENTO IN ('R', 'D')),
   DESCRICAO VARCHAR(200) NOT NULL,
   VALOR NUMERIC(10,2) NOT NULL
)


CREATE TABLE TB_RESUMO_FINANCEIRO (
   CD_USUARIO INT NOT NULL,
   MES INT NOT NULL,
   ANO INT NOT NULL,
   TOTAL_RECEITAS NUMERIC(10,2) NOT NULL,
   TOTAL_DESPESAS NUMERIC(10,2) NOT NULL,
   PRIMARY KEY(CD_USUARIO, MES, ANO)
)

