CREATE DATABASE GATILHOS
USE GATILHOS

CREATE TABLE TB_ALUNO (
    MATRICULA INT NOT NULL PRIMARY KEY,
    NOME VARCHAR(50) NOT NULL,
    RG INT NULL,
    ENDERECO VARCHAR(100) NULL,
    TELEFONE VARCHAR (20) NULL,
)

CREATE TABLE TB_LOG_PENDENCIAS (
  MATRICULA INT,
  NOME VARCHAR(50),
  PENDENCIA VARCHAR(200)
)
/*
	==================== QUESTAO 01 ====================
*/
CREATE TRIGGER TG_ALUNO_PENDENCIA ON TB_ALUNO
AFTER INSERT
AS
BEGIN
	DECLARE @MATRICULA INT, @NOME VARCHAR(50), @RG INT, @ENDERECO VARCHAR(100), @TELEFONE VARCHAR(20)

	DECLARE CURSOR_INSERTED CURSOR
	FOR
	SELECT MATRICULA, NOME, RG, ENDERECO, TELEFONE FROM INSERTED

	-- CURSOR PARA PERCORRER OS ITENS INSERIDOS.
	OPEN CURSOR_INSERTED
	FETCH CURSOR_INSERTED INTO @MATRICULA, @NOME, @RG, @ENDERECO, @TELEFONE

	WHILE(@@FETCH_STATUS = 0)
	BEGIN
		DECLARE @MSG VARCHAR(100)

		IF(@RG IS NULL)
		BEGIN
			SET @MSG = 'FALTA RG'
			INSERT INTO TB_LOG_PENDENCIAS(MATRICULA, NOME, PENDENCIA) VALUES (@MATRICULA, @NOME, @MSG)
		END

		IF(@TELEFONE IS NULL)
		BEGIN
			SET @MSG = 'FALTA TELEFONE'
			INSERT INTO TB_LOG_PENDENCIAS(MATRICULA, NOME, PENDENCIA) VALUES (@MATRICULA, @NOME, @MSG)
		END

		IF(@ENDERECO IS NULL)
		BEGIN
			SET @MSG = 'FALTA ENDERECO'
			INSERT INTO TB_LOG_PENDENCIAS(MATRICULA, NOME, PENDENCIA) VALUES (@MATRICULA, @NOME, @MSG)
		END

		FETCH CURSOR_INSERTED INTO @MATRICULA, @NOME, @RG, @ENDERECO, @TELEFONE
	END

	CLOSE CURSOR_INSERTED
	DEALLOCATE CURSOR_INSERTED
END

/*
	==================== QUESTAO 02 ====================
*/
CREATE TRIGGER TG_ALUNO_UPDATE ON TB_ALUNO
AFTER UPDATE
AS
BEGIN
	PRINT('')
END


/*
	======== TESTES ========
*/
DROP TRIGGER TG_ALUNO_PENDENCIA
TRUNCATE TABLE TB_ALUNO
TRUNCATE TABLE TB_LOG_PENDENCIAS

INSERT INTO TB_ALUNO (MATRICULA, NOME, RG, ENDERECO, TELEFONE) 
VALUES (1,'GABRIEL', 55, 'RUA X', NULL),
(2,'JOAO', 55, NULL, NULL),
(3,'ROBERTO', NULL, 'RUA X', 555),
(4,'CAIO', 55, 'RUA X', 55555)

SELECT * FROM TB_LOG_PENDENCIAS
SELECT * FROM TB_ALUNO